-- Jalankan script ini di Supabase Dashboard -> SQL Editor -> New query

-- 1. Tabel soal kuis
create table if not exists questions (
  id bigint generated by default as identity primary key,
  question text not null,
  choices jsonb not null,        -- array 4 string, contoh: ["A","B","C","D"]
  correct_index int not null check (correct_index between 0 and 3),
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard', 'very_hard')),
  created_at timestamptz default now()
);

create index if not exists questions_difficulty_idx on questions (difficulty);

-- 2. Tabel skor / leaderboard
create table if not exists scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 40),
  questions_answered int not null default 0,
  prize_amount bigint not null default 0,
  prize_label text not null default 'Rp 0',
  result text not null default 'lost', -- 'lost' atau 'won'
  created_at timestamptz default now()
);

-- 3. Aktifkan Row Level Security
alter table questions enable row level security;
alter table scores enable row level security;

-- 4. Policy: siapa saja (anon) boleh BACA soal & leaderboard
create policy "Public can read questions"
  on questions for select
  using (true);

create policy "Public can read scores"
  on scores for select
  using (true);

-- 5. Policy: siapa saja (anon) boleh INSERT skor sendiri ke leaderboard
create policy "Public can insert own score"
  on scores for insert
  with check (true);

-- Catatan: tidak ada policy UPDATE/DELETE untuk publik, jadi soal & skor
-- cuma bisa diubah/dihapus lewat Supabase Dashboard (pakai service role / kamu sebagai owner).

-- 6. Setelah ini, jalankan file seed_questions.sql buat ngisi 200 soal contoh
--    (50 easy, 50 medium, 50 hard, 50 very_hard). Tambah soal sendiri kapan
--    aja lewat Table Editor -> questions, cukup isi question / choices /
--    correct_index / difficulty -- otomatis ikut ke dalam pool random.
